### ISSUE TITLE
abstract casa config info to `config/casa.yml`

### ISSUE THREAD

**Issue by stevenolen** [ucla-oarc-mobile/casa-on-rails#73]
Similarly to how it's handled in #71. This would help to ensure that we don't need to replicate the `production.rb` config elements in chef in order to properly deploy casa config items.

**Comment by stevenolen** [comment]
Shouldn't this block: https://github.com/ucla/casa-on-rails/blob/master/config/initializers/casa.rb#L10-L13

instead be:

``` ruby
if File.exists?('config/casa.yml')
  config.merge!(YAML.load_file('config/casa.yml').deep_symbolize_keys)
end
```

Since I'm getting this error when trying to use:

```
/Users/steve/.rvm/gems/ruby-2.1.1/gems/railties-4.1.4/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `merge!' for #<Rails::Application::Configuration:0x000001059647f8> (NoMethodError)
    from /Users/steve/git/casa-on-rails/config/initializers/casa.rb:12:in `<top (required)>'
```
